# SPDX-FileCopyrightText:  Copyright 2024 Roland Csaszar
# SPDX-License-Identifier: MIT
#
# Project:  go-gap-buffer
# File:     test.yml
# Date:     08.Feb.2024
#
# ==============================================================================

name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  coverage:
    strategy:
      matrix:
        go: ['1.21']
        os: [macos-latest, ubuntu-latest]
    name: Tests ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.6'

    - name: Run tests with coverage
      run: go test -coverprofile=coverage.txt -covermode=atomic

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.0.1
      env:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: Release-Candidate/go-gap-buffer
